# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PremierLeagueStandings' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PremierLeagueStandings

pod 'SVGKit'

end
